import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Menu, X, Mountain, MapPin, Compass, Leaf, Heart, Clock3, Check, Instagram, MoveUpRight, SlidersHorizontal, Infinity, Phone, Mail, BedDouble, Car, Plane, MessageCircle } from 'lucide-react';
import { site, trips, faqs, gallery } from './data/content';
import './App.css';

function Brand() {
  return <a className="brand" href="#home" aria-label="TrippyGo home">
    <img className="brand-logo" src={site.logo} alt="" width="46" height="46"/>
    <span className="brand-words"><span>TrippyGo<Infinity className="brand-infinity" size={23}/></span><small>{site.tagline}</small></span>
  </a>;
}
function App() {
  const [menu, setMenu] = useState(false);
  const [filter, setFilter] = useState('All escapes');
  const [destination, setDestination] = useState('Anywhere sounds good');
  const [style, setStyle] = useState('Any kind of escape');
  const [selected, setSelected] = useState(null);
  const [copied, setCopied] = useState(false);
  const dialog = useRef(null);
  const visible = trips.filter(t => (filter === 'All escapes' || t.category === filter) && (destination === 'Anywhere sounds good' || t.destination === destination));
  useEffect(() => {
    if (selected) { dialog.current.showModal(); document.body.style.overflow = 'hidden'; }
    else { dialog.current?.close(); document.body.style.overflow = ''; }
    return () => { document.body.style.overflow = ''; };
  }, [selected]);
  const contact = site.whatsapp ? `https://wa.me/${site.whatsapp}?text=${encodeURIComponent(`Hi TrippyGo! I'd love to plan ${selected ? `the ${selected.destination} escape` : 'a trip'}.`)}` : site.instagram;
  function explore(e) { e.preventDefault(); setFilter(style === 'Any kind of escape' ? 'All escapes' : style); document.getElementById('escapes').scrollIntoView({ behavior: 'smooth' }); }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header" id="home"><div className="container nav-wrap"><Brand/><nav id="navigation" className={menu ? 'navigation is-open' : 'navigation'} aria-label="Main navigation">{[['Escapes', 'escapes'], ['The TrippyGo way', 'about'], ['Travel notes', 'notes']].map(([text, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{text}</a>)}</nav><a className="button button-green nav-cta" href="#contact">Let’s plan a trip <ArrowUpRight size={17}/></a><button className="menu-button" aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div></header>
    <main id="main">
      <section className="hero" aria-labelledby="hero-title">
        <div className="container hero-layout">
          <div className="hero-copy">
            <div className="hero-label"><span/> WHERE EVERY TRIP FEELS SPECIAL</div>
            <h1 id="hero-title"><span className="handwritten">Pack your</span><span className="dream-title">DREAMS<Infinity aria-hidden="true"/></span></h1>
            <p>Into the forests. Beyond the everyday.<br/>Trips, stays, and little adventures that become your favourite stories.</p>
            <div className="hero-actions"><a className="button button-yellow" href="#escapes">Find my next adventure <ArrowUpRight size={19}/></a><a className="hero-chat" href={contact} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Let’s talk travel</a></div>
            <div className="hero-footnote"><span className="route-doodle" aria-hidden="true">↝</span><span>Couples · Families · Your favourite people<br/><strong>You bring the dreams. We’ll bring the plan.</strong></span></div>
          </div>
          <div className="hero-collage">
            <div className="travel-stamp"><span>LET’S GET</span><Compass size={32} strokeWidth={1.2}/><span>LOST & FOUND</span></div>
            <figure className="hero-polaroid main-polaroid"><img src={site.heroImage} alt="A warmly lit treehouse tucked into a green forest, from TrippyGo’s Instagram" fetchpriority="high"/><figcaption>A little out of the ordinary. <Heart size={17}/></figcaption></figure>
            <figure className="hero-polaroid small-polaroid"><img src="./images/woodland-stay.webp" alt="A-frame woodland stay featured by TrippyGo" fetchpriority="high"/><figcaption>Nature. Peace. Memories.</figcaption></figure>
            <span className="collage-note">Your next story<br/>starts here <span aria-hidden="true">↗</span></span>
          </div>
        </div>
      </section>
      <div className="adventure-strip" aria-label="Travel experiences"><span>GOOD PEOPLE</span><span aria-hidden="true">✳</span><span>GREAT PLACES</span><span aria-hidden="true">✳</span><span>MEMORIES FOREVER</span><Infinity size={26}/><span>LET’S TRIP TOGETHER</span><span aria-hidden="true">✳</span></div>
      <div className="container search-container"><form className="trip-search" onSubmit={explore}><div className="search-intro"><Compass size={23}/><strong>Your next<br/>“let’s go” moment.</strong></div><label><span><MapPin size={14}/> WHERE TO?</span><select value={destination} onChange={e => setDestination(e.target.value)}><option>Anywhere sounds good</option>{trips.map(t => <option key={t.id}>{t.destination}</option>)}</select></label><label><span><Leaf size={14}/> YOUR KIND OF TRIP</span><select value={style} onChange={e => setStyle(e.target.value)}><option>Any kind of escape</option><option>Mountains</option><option>Backwaters</option><option>Beaches</option></select></label><button className="button button-green" type="submit">Explore escapes <ArrowRight size={18}/></button></form></div>
      <div className="container promise-strip"><span><Leaf/> A little closer to nature</span><span><SlidersHorizontal/> Personalised to your pace</span><span><Heart/> Planned with a personal touch</span></div>
      <section id="escapes" className="section container"><div className="section-heading"><div><span className="eyebrow">A WEEKEND AWAY. A WORLD TO EXPLORE.</span><h2>CHOOSE YOUR<br/><em>kind of escape.</em></h2></div><p>For the long weekends, the spontaneous plans,<br className="desktop-break"/> and the “we really needed this” getaways.</p></div><div className="filter-row"><div className="filters" aria-label="Filter escapes">{['All escapes', 'Mountains', 'Backwaters', 'Beaches'].map(f => <button key={f} aria-pressed={filter === f} className={filter === f ? 'filter active' : 'filter'} onClick={() => { setFilter(f); setDestination('Anywhere sounds good'); }}>{f === 'All escapes' && <Compass size={15}/>} {f}</button>)}</div><span className="trip-count" aria-live="polite">{visible.length} places to disconnect</span></div><div className="trip-grid">{visible.map(t => <article className="trip-card" key={t.id}><button className="trip-photo" onClick={() => setSelected(t)} aria-label={`Explore ${t.destination}`}><img src={t.image} alt={t.alt} loading="lazy"/><span className="photo-tag">{t.tag}</span><span className="poster-destination">{t.destination}</span><span className="photo-location"><MapPin size={14}/>{t.region}, India</span><span className="photo-arrow"><ArrowUpRight size={21}/></span></button><div className="trip-body"><span className="trip-duration"><Clock3 size={13}/>{t.duration}<span>·</span>{t.category}</span><h3><button onClick={() => setSelected(t)}>{t.title}</button></h3><p>{t.description}</p><div className="trip-card-bottom"><span>Made for you <small>Get a personalised quote</small></span><button aria-label={`View ${t.destination} itinerary`} onClick={() => setSelected(t)}><ArrowUpRight size={21}/></button></div></div></article>)}</div>{visible.length === 0 && <div className="empty-state"><Compass size={32}/><h3>A different kind of escape?</h3><p>No trip ideas match those filters. Explore all escapes or ask us to plan something personal.</p><button className="button button-green" onClick={() => {setFilter('All escapes'); setDestination('Anywhere sounds good');}}>Show all escapes <ArrowRight size={17}/></button></div>}<p className="sample-note">A little inspiration for your next trip. Itineraries are customisable; availability and final pricing are confirmed on enquiry.</p></section>
      <section className="services-section container" aria-labelledby="services-title"><div><span className="eyebrow">THE WHOLE TRIP, SORTED</span><h2 id="services-title">More than <em>a getaway.</em></h2></div><div className="service-grid">{[[Compass,'Custom packages','Couple, family & group trips'],[BedDouble,'Stays & resorts','Find your kind of hideaway'],[Car,'Cab services','Make the journey part of the trip'],[Plane,'International tours','Take your dreams a little further']].map(([Icon,title,description]) => <a href={contact} key={title} target="_blank" rel="noreferrer"><Icon size={25} strokeWidth={1.4}/><h3>{title}</h3><p>{description}</p><ArrowUpRight className="service-arrow" size={17}/></a>)}</div></section>
      <section className="about-section" id="about"><div className="container about-grid"><div className="about-art"><img src="./images/sunset-stay.webp" alt="A TrippyGo holiday stay under a golden evening sky" loading="lazy"/><div className="photo-note">Let’s trip<br/><em>together!</em><span>↗</span></div><div className="small-stamp"><Mountain size={24}/><span>GO SLOW.<br/>FEEL MORE.</span></div></div><div className="about-copy"><span className="eyebrow">SMALL TEAM. BIG WANDERLUST.</span><h2>BIG DREAMS.<br/><em>Personal plans.</em></h2><p>We believe the best trips leave you with stories, not a to-do list. TrippyGo is here to bring a little more ease, a little more discovery, and a whole lot of heart to your next getaway.</p><div className="value-item"><span><Compass size={21}/></span><div><h3>Your trip, your rhythm</h3><p>Early starts or slow mornings? We plan around you.</p></div></div><div className="value-item"><span><Leaf size={21}/></span><div><h3>Good places, thoughtfully picked</h3><p>Nature, local experiences, and room to simply be.</p></div></div><div className="value-item"><span><Heart size={21}/></span><div><h3>A real person, a conversation away</h3><p>Talk to the people helping bring your trip to life.</p></div></div><a href="#contact" className="text-link">Get to know your next adventure <ArrowUpRight size={18}/></a></div></div></section>
      <section className="section container how-section" id="notes"><span className="eyebrow">FROM “SOMEDAY” TO “LET’S GO”</span><div className="section-heading"><h2>YOU DREAM IT.<br/><em>We’ll plan it.</em></h2><a href={site.instagram} target="_blank" rel="noreferrer" className="text-link">Say hello on Instagram <ArrowUpRight size={18}/></a></div><div className="steps">{[['01','Tell us your daydream','A place, a mood, a weekend. Give us a little idea of what you have in mind.'],['02','We make it a plan','Together, we’ll work out the places, pace, and little details that feel right.'],['03','You make the memories','Once your plan is confirmed, pack your bags. There’s a world waiting outside.']].map(([n,h,p]) => <div key={n}><span className="step-number">{n}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>
      <section className="instagram-section">
        <div className="container">
          <div className="section-heading"><div><span className="eyebrow">POSTCARDS FROM OUR CORNER OF THE WORLD</span><h2>A LITTLE WILD.<br/><em>A lot to remember.</em></h2></div><a href={site.instagram} className="text-link" target="_blank" rel="noreferrer"><Instagram size={18}/>{site.handle}<ArrowUpRight size={18}/></a></div>
          <div className="social-gallery">{gallery.map(item => <a key={item.image} href={site.instagram} target="_blank" rel="noreferrer" className="social-card"><div className="social-image"><img src={item.image} alt={item.alt} loading="lazy"/><Instagram size={19}/></div><div className="social-caption"><span>{item.type}</span><h3>{item.label}</h3><ArrowUpRight size={20}/></div></a>)}</div>
        </div>
      </section>
      <section className="section container faq-section"><div><span className="eyebrow">BEFORE YOU PACK</span><h2>BEFORE YOU GO.<br/><em>The little details.</em></h2></div><div className="faqs">{faqs.map(([q,a]) => <details key={q}><summary>{q}<span className="faq-plus">+</span></summary><p>{a}</p></details>)}</div></section>
      <section className="contact-section container" id="contact"><div className="contact-panel"><div className="contact-decoration" aria-hidden="true"><Compass size={280} strokeWidth={0.5}/></div><span className="eyebrow">YOUR OUT-OF-OFFICE ERA STARTS HERE</span><h2>THE WORLD IS CALLING.<br/><em>Let’s trip together.</em></h2><p>Tell us where your mind wanders.<br/>We’ll help you find your way there.</p><a className="button button-cream" href={contact} target="_blank" rel="noreferrer">Chat with us on WhatsApp <MessageCircle size={19}/></a><div className="contact-details">{site.phones.map(phone => <a key={phone.value} href={`tel:${phone.value}`}><Phone size={14}/>{phone.label}</a>)}<a href={`mailto:${site.email}`}><Mail size={14}/>{site.email}</a></div></div></section>
    </main><footer className="container footer"><div className="footer-top"><div><Brand/><p>Where every trip feels special.</p></div><div className="footer-links"><a href="#escapes">Explore escapes</a><a href="#about">Our story</a><a href={site.instagram} target="_blank" rel="noreferrer" aria-label="TrippyGo on Instagram"><Instagram size={19}/></a><a href="#home" aria-label="Back to top"><MoveUpRight size={22}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} TrippyGo. Made for the memories.</span><span>With a little love & a lot of wanderlust <Heart size={12}/></span></div></footer>
    <dialog ref={dialog} aria-label={selected ? `${selected.destination} trip details` : "Trip details"} className="trip-dialog" onCancel={() => setSelected(null)} onClick={e => { if(e.target === dialog.current) setSelected(null); }} onClose={() => {setSelected(null); setCopied(false);}}>{selected && <><button className="dialog-close" aria-label="Close itinerary" onClick={() => setSelected(null)}><X size={22}/></button><img className="dialog-image" src={selected.image} alt={selected.alt}/><div className="dialog-body"><span className="eyebrow">{selected.destination} · {selected.duration}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="highlights">{selected.highlights.map(h => <span key={h}><Check size={14}/>{h}</span>)}</div><h3>Your trip could look like this</h3><ol className="itinerary">{selected.itinerary.map((day,i) => <li key={day}><strong>Day {i+1}</strong><span>{day}</span></li>)}</ol><p className="sample-note">Suggested itinerary. Stays, transport, activities, availability, and pricing will be confirmed in your personal quote.</p><a className="button button-green" href={contact} target="_blank" rel="noreferrer">Ask us about this escape <ArrowUpRight size={18}/></a><button className="copy-button" onClick={async () => {try {await navigator.clipboard.writeText(`Hi TrippyGo! I’m interested in your ${selected.destination} escape (${selected.duration}). Can you help me plan a trip?`); setCopied(true);} catch {setCopied('failed');}}}>{copied === true ? 'Copied! Paste it into your message.' : copied === 'failed' ? 'Copy unavailable — mention this destination in your message.' : 'Copy a trip enquiry to send'} </button><span className="sr-only" role="status">{copied === true ? 'Trip enquiry copied' : ''}</span></div></>}</dialog>
  </>;
}
export default App;
